resources:
- name: master
  type: git
  source:
    uri: https://github.com/tbatard/hello-concourse.git
    branch: master
- name: development
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: development
    skip_cert_check: false

jobs:
- name: build & deploy
  serial: true
  plan:
  - get: master
    trigger: true
  - task: build
    config:
      inputs:
      - name: master
      outputs:
      - name: build-artifact
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: openjdk
          tag: 8
      run:
        dir: master
        path: sh
        args:
        - -exc
        - |
          ./gradlew build
          mv build/libs/*.jar ../build-artifact/
  - put: development
    params:
      manifest: master/manifest.yml
      path: build-artifact/hello-concourse-0.0.1-SNAPSHOT.jar
      environment_variables:
        MESSAGE_WELCOME: {{message-welcome}}