resources:
- name: master
  type: git
  source:
    uri: {{git-repo}}
    branch: master
    private_key: {{git-private-key}}

jobs:
- name: build
  serial: true
  plan:
  - get: repo
    resource: master
    trigger: true
  - task: build
    file: repo/ci/tasks/build.yml
