resources:
- name: master
  type: git
  source:
    uri: {{git-repo}}
    branch: master
    private_key: {{git-private-key}}

jobs:
- name: build
  serial: true
  plan:
  - get: master
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: openjdk
          tag: 8
      inputs:
      - name: master
      run:
        dir: master
        path: ./gradlew
        args: ['build']
